---
# Create Groups
- name: Create Admin Group
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: "openshift.{{ tenant_id }}{{ item | lower }}.admin.users"
      users: null
- name: Create User Group
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: "openshift.{{ tenant_id }}{{ item | lower }}.login.users"
      users: null
- name: Create Appsupport Group
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: "openshift.{{ tenant_id }}{{ item | lower }}.appsupport.users"
      users: null