---
- name: Create namespaces
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        name: "{{ tenant_id }}"
        api_version: v1
        kind: Namespace
        state: present
    - name: Print out env
      ansible.builtin.debug:
        var: tenant_env
    - name: Print out size
      ansible.builtin.debug:
        var: tenant_shirt_size
    - name: Print out primary owner
      ansible.builtin.debug:
        var: primary_owner
    - name: Print out secondary owner
      ansible.builtin.debug:
        var: secondary_owner

    - name: Set size dq xs
      when: tenant_env in ['Dev', 'QA'] and tenant_shirt_size == "Extra Small"
      ansible.builtin.set_fact:
        pod_quota: 10
        services_quota: 5
        cpu_req: 500m
        cpu_limit: 1000m
        mem_req: 4Gi
        mem_lim: 8Gi
    - name: Set size dq s
      when: tenant_env in ['Dev', 'QA'] and tenant_shirt_size == "Small"
      ansible.builtin.set_fact:
        pod_quota: 30
        services_quota: 10
        cpu_req: 1000m
        cpu_limit: 3000m
        mem_req: 8Gi
        mem_lim: 16Gi
    - name: Set size dq m
      when: tenant_env in ['Dev', 'QA'] and tenant_shirt_size == "Medium"
      ansible.builtin.set_fact:
        pod_quota: 50
        services_quota: 15
        cpu_req: 3000m
        cpu_limit: 6000m
        mem_req: 12Gi
        mem_lim: 24Gi
    - name: Set size dq l
      when: tenant_env in ['Dev', 'QA'] and tenant_shirt_size == "Large"
      ansible.builtin.set_fact:
        pod_quota: 75
        services_quota: 15
        cpu_req: 6000m
        cpu_limit: 9000m
        mem_req: 16Gi
        mem_lim: 32Gi
    - name: Set size sp xs
      when: tenant_env in ['Stage', 'Prod'] and tenant_shirt_size == "Extra Small"
      ansible.builtin.set_fact:
        pod_quota: 30
        services_quota: 10
        cpu_req: 1000m
        cpu_limit: 2000m
        mem_req: 8Gi
        mem_lim: 16Gi
    - name: Set size sp s
      when: tenant_env in ['Stage', 'Prod'] and tenant_shirt_size == "Small"
      ansible.builtin.set_fact:
        pod_quota: 75
        services_quota: 15
        cpu_req: 3000m
        cpu_limit: 6000m
        mem_req: 12Gi
        mem_lim: 24Gi
    - name: Set size sp m
      when: tenant_env in ['Stage', 'Prod'] and tenant_shirt_size == "Medium"
      ansible.builtin.set_fact:
        pod_quota: 75
        services_quota: 15
        cpu_req: 6000m
        cpu_limit: 9000m
        mem_req: 16Gi
        mem_lim: 32Gi
    - name: Set size sp l
      when: tenant_env in ['Stage', 'Prod'] and tenant_shirt_size == "Large"
      ansible.builtin.set_fact:
        pod_quota: 100
        services_quota: 30
        cpu_req: 9000m
        cpu_limit: 18000m
        mem_req: 32Gi
        mem_lim: 64Gi