---
- name: Create namespaces
  hosts: localhost
  gather_facts: false
  vars_files: structure.yml
  vars:
    business_unit: Diagnostics
  pre_tasks:
    - name: Import the custom task file
      ansible.builtin.include_tasks: get_instance.yml
      loop: "{{ namespaces }}"

  roles:
    - create_namespace
  post_tasks:
    - name: ResourceQuotas
      ansible.builtin.include_role: 
        name: create_resourcequotas
      loop: "{{ namespaces }}"

    - name: RoleBindings
      ansible.builtin.include_role: 
        name: create_rolebindings
      loop: "{{ namespaces }}"

    - name: Groups
      ansible.builtin.include_role: 
        name: create_groups
      loop: "{{ namespaces }}"

  #   - name: GitOps Sync
  #     ansible.builtin.include_role:
  #       name: create_gitops
  #     loop: "{{ namespaces }}"