---
# Set ResourceQuota sizes and create ResourceQuotas
- name: Set nonprod prefix
  when: item in ['Dev', 'QA']
  ansible.builtin.set_fact:
    prefix: "{{ nonprod_shirt_size | lower | replace(' ', '_') }}_nonprod_"

- name: Set prod prefix
  when: item in ['Stage', 'Prod']
  ansible.builtin.set_fact:
    prefix: "{{ nonprod_shirt_size | lower | replace(' ', '_') }}_prod_"

- name: check reqs
  ansible.builtin.debug:
    msg:
      - requests.cpu: "{{ prefix ~ 'request_cpu' }}"
      - requests.memory: "{{ prefix ~ 'request_memory' }}"
      - limits.cpu: "{{ prefix ~ 'limit_cpu' }}"
      - limits.memory: "{{ prefix ~ 'limit_memory' }}"
      - pods: "{{ prefix ~ 'pods' }}"
      - services: "{{ prefix ~ 'services' }}"

- name: Create Resource Quota
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: resource-quota
        namespace: "{{ tenant_id }}-{{ item | lower }}"
      spec:
        hard:
          requests.cpu: "{{ prefix ~ 'request_cpu' }}"
          requests.memory: "{{ prefix ~ 'request_memory' }}"
          limits.cpu: "{{ prefix ~ 'limit_cpu' }}"
          limits.memory: "{{ prefix ~ 'limit_memory' }}"
          pods: "{{ prefix ~ 'pods' }}"
          services: "{{ prefix ~ 'services' }}"