---
# Create ResourceQuotas
- name: Set nonprod prefix
  ansible.builtin.set_fact:
    prefix: "{{ nonprod_shirt_size | lower | replace(' ', '_') }}_nonprod_"
  when: item in ['Dev', 'QA']

- name: Set prod prefix
  ansible.builtin.set_fact:
    prefix: "{{ nonprod_shirt_size | lower | replace(' ', '_') }}_prod_"
  when: item in ['Stage', 'Prod']

- name: Create Resource Quota
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: resource-quota
        namespace: "{{ tenant_id }}-{{ item | lower }}"
      spec:
        hard:
          # NOTE: ResourceQuotas for each size are defined in vars/main.yml
          requests.cpu: "{{ vars[prefix ~ 'request_cpu'] }}"
          requests.memory: "{{ vars[prefix ~ 'request_memory'] }}"
          limits.cpu: "{{ vars[prefix ~ 'limit_cpu'] }}"
          limits.memory: "{{ vars[prefix ~ 'limit_memory'] }}"
          pods: "{{ vars[prefix ~ 'pods'] }}"
          services: "{{ vars[prefix ~ 'services'] }}"