---
# Create ResourceQuotas
- name: Set vars
  ansible.builtin.set_fact:
    cpu_req: "{{ item.size | lower | replace(' ', '_') }}_request_cpu"
    mem_req: "{{ item.size | lower | replace(' ', '_') }}_request_memory"
    cpu_lim: "{{ item.size | lower | replace(' ', '_') }}_limit_cpu"
    mem_lim: "{{ item.size | lower | replace(' ', '_') }}_limit_memory"
    pods: "{{ item.size | lower | replace(' ', '_') }}_pods"
    servs: "{{ item.size | lower | replace(' ', '_') }}_services"

- name: Create Resource Quota
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: resource-quota
        namespace: "{{ item.name }}"
      spec:
        hard:
          # NOTE: ResourceQuotas for each size are defined in vars/main.yml
          requests.cpu: "{{ vars[cpu_req] }}"
          requests.memory: "{{ vars[mem_req] }}"
          limits.cpu: "{{ vars[cpu_lim] }}"
          limits.memory: "{{ vars[mem_lim] }}"
          pods: "{{ vars[pods] }}"
          services: "{{ vars[servs] }}"