---
#### Set ResourceQuota Sizes and create ResourceQuotas (TODO: role)
- name: Set ResourceQuota sizes and create ResourceQuota
  block:
  - name: Set size dq xs
    when: item in ['Dev', 'QA'] and nonprod_shirt_size == "Extra Small"
    ansible.builtin.set_fact:
      pod_quota: 10
      services_quota: 5
      cpu_req: 500m
      cpu_limit: 1000m
      mem_req: 4Gi
      mem_limit: 8Gi
  - name: Set size dq s
    when: item in ['Dev', 'QA'] and nonprod_shirt_size == "Small"
    ansible.builtin.set_fact:
      pod_quota: 30
      services_quota: 10
      cpu_req: 1000m
      cpu_limit: 3000m
      mem_req: 8Gi
      mem_limit: 16Gi
  - name: Set size dq m
    when: item in ['Dev', 'QA'] and nonprod_shirt_size == "Medium"
    ansible.builtin.set_fact:
      pod_quota: 50
      services_quota: 15
      cpu_req: 3000m
      cpu_limit: 6000m
      mem_req: 12Gi
      mem_limit: 24Gi
  - name: Set size dq l
    when: item in ['Dev', 'QA'] and nonprod_shirt_size == "Large"
    ansible.builtin.set_fact:
      pod_quota: 75
      services_quota: 15
      cpu_req: 6000m
      cpu_limit: 9000m
      mem_req: 16Gi
      mem_limit: 32Gi
  - name: Set size sp xs
    when: item in ['Stage', 'Prod'] and prod_shirt_size == "Extra Small"
    ansible.builtin.set_fact:
      pod_quota: 30
      services_quota: 10
      cpu_req: 1000m
      cpu_limit: 2000m
      mem_req: 8Gi
      mem_limit: 16Gi
  - name: Set size sp s
    when: item in ['Stage', 'Prod'] and nonprod_shirt_size == "Small"
    ansible.builtin.set_fact:
      pod_quota: 75
      services_quota: 15
      cpu_req: 3000m
      cpu_limit: 6000m
      mem_req: 12Gi
      mem_limit: 24Gi
  - name: Set size sp m
    when: item in ['Stage', 'Prod'] and nonprod_shirt_size == "Medium"
    ansible.builtin.set_fact:
      pod_quota: 75
      services_quota: 15
      cpu_req: 6000m
      cpu_limit: 9000m
      mem_req: 16Gi
      mem_limit: 32Gi
  - name: Set size sp l
    when: item in ['Stage', 'Prod'] and nonprod_shirt_size == "Large"
    ansible.builtin.set_fact:
      pod_quota: 100
      services_quota: 30
      cpu_req: 9000m
      cpu_limit: 18000m
      mem_req: 32Gi
      mem_limit: 64Gi
  - name: Print size quotas
    ansible.builtin.debug:
      msg:
        - "pods: {{ pod_quota }}"
        - "services: {{ services_quota }}"
        - "CPU Request: {{ cpu_req }}"
        - "CPU Limit: {{ cpu_limit }}"
        - "Memory Request: {{ mem_req }}"
        - "Memory Limit: {{ mem_limit }}"

  - name: Create Resource Quota
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: resource-quota
          namespace: "{{ tenant_id }}-{{ item | lower }}"
        spec:
          hard:
            requests.cpu: "{{ cpu_req }}"
            requests.memory: "{{ mem_req }}"
            limits.cpu: "{{ cpu_limit }}"
            limits.memory: "{{ mem_limit }}"
            pods: "{{ pod_quota }}"
            services: "{{ services_quota }}"