---
controller_credentials:
- name: ocp-kubeconfig
  organization: Platform Automation
  credential_type: Kubeconfig
  inputs:
    kube_config: "{{ kube_conf }}"

- name: git-token
  organization: Platform Automation
  credential_type: Git Runtime Token
  inputs:
    git_username: "{{ lookup('env', 'GIT_USER') }}"
    git_token: "{{ lookup('env', 'GIT_TOKEN') }}"