---
controller_credential_types:
- name: Kubeconfig
  inputs:
    fields:
      - id: kube_config
        type: string
        label: kubeconfig
        secret: true
        multiline: true
    required:
      - kube_config
  injectors:
    env:
      K8S_AUTH_KUBECONFIG: "{{ '{{ tower.filename.kubeconfig }}' }}"
    file:
      template.kubeconfig: "{{ '{{ kube_config }}' }}"

- name: Git Runtime Token
  inputs:
    fields:
      - id: git_username
        type: string
        label: Git Username
      - id: git_token
        type: string
        label: Git Personal Access Token
        secret: true
    required:
      - git_username
      - git_token
  injectors:
    env:
      GIT_USER: "{{ '{{ git_username }}' }}"
      GIT_TOKEN: "{{ '{{ git_token }}' }}"
