---
controller_projects:
  - name: Onboarding
    organization: Platform Automation
    scm_type: git
    scm_url: https://github.com/calzone-cannoli/namespace-creation
    scm_branch: main
    credentials:
      - git
    description: Project for onboarding namespaces