---
# Namespace Definition (mirrors create_namespace role)
apiVersion: v1
kind: Namespace
metadata:
  name: "test-tenant-4-stage"
  labels:
    tenant: "test-tenant-4"
    environment: "stage"
    provisioned-by: ansible-automation-platform

---
# Resource Quota Definition
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: "test-tenant-4-stage"
spec:
  hard:
    # NOTE: ResourceQuotas for each size are defined in vars/main.yml
    requests.cpu: "6000m"
    requests.memory: "16Gi"
    limits.cpu: "9000m"
    limits.memory: "32Gi"
    pods: "75"
    services: "15"

---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: "openshift.test-tenant-4stage.admin.users"
users: null

---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: "openshift.test-tenant-4stage.login.users"
users: null

---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: "openshift.test-tenant-4stage.appsupport.users"
users: null

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rb
  namespace: "test-tenant-4-stage"
subjects:
- kind: User
  name: system:serviceaccount:ucd-agent:ucd
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: openshift.staging.admin.users
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: "openshift.test-tenant-4stage.admin.users"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-rb
  namespace: "test-tenant-4-stage"
subjects:
- kind: Group
  name: openshift.devops.users
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: openshift.middleware.users
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: openshift.staging.login.users
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: "openshift.test-tenant-4stage.login.users"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appsupport-rb
  namespace: "test-tenant-4-stage"
subjects:
- kind: Group
  name: "openshift.test-tenant-4stage.appsupport.users"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: labcorp-app-support
  apiGroup: rbac.authorization.k8s.io

