---
#### Create RoleBindings
- name: Dev/QA RoleBindings
  when: item in ['Dev', 'QA']
  ansible.builtin.import_tasks: dev_qa_rb.yml
      
- name: Stage RoleBindings
  when: item == 'Stage'
  ansible.builtin.import_tasks: stage_rb.yml

- name: Prod RoleBindings
  when: item == 'Prod'
  ansible.builtin.import_tasks: prod_rb.yml