---
- name: Create Admin RoleBinding for Stage
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: admin-rb
        namespace: "{{ item.name }}"
      subjects:
      - kind: User
        name: system:serviceaccount:ucd-agent:ucd
        apiGroup: rbac.authorization.k8s.io
      - kind: Group
        name: openshift.staging.admin.users
        apiGroup: rbac.authorization.k8s.io
      - kind: Group
        name: "openshift.{{ tenant_id }}stage.admin.users"
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: admin
        apiGroup: rbac.authorization.k8s.io
- name: Create View RoleBinding for Stage
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: view-rb
        namespace: "{{ item.name }}"
      subjects:
      - kind: Group
        name: openshift.devops.users
        apiGroup: rbac.authorization.k8s.io
      - kind: Group
        name: openshift.middleware.users
        apiGroup: rbac.authorization.k8s.io
      - kind: Group
        name: openshift.staging.login.users
        apiGroup: rbac.authorization.k8s.io
      - kind: Group
        name: "openshift.{{ tenant_id }}stage.login.users"
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: view
        apiGroup: rbac.authorization.k8s.io
- name: Create AppSupport RoleBinding for Stage
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: appsupport-rb
        namespace: "{{ item.name }}"
      subjects:
      - kind: Group
        name: "openshift.{{ tenant_id }}stage.appsupport.users"
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: labcorp-app-support
        apiGroup: rbac.authorization.k8s.io