---
# Namespace Definition (mirrors create_namespace role)
apiVersion: v1
kind: Namespace
metadata:
  name: "aaa-test-prod"
  labels:
    tenant: "aaa-test"
    environment: "prod"
    provisioned-by: ansible-automation-platform

---
# Resource Quota Definition
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: "aaa-test-prod"
spec:
  hard:
    # NOTE: ResourceQuotas for each size are defined in vars/main.yml
    requests.cpu: "9000m"
    requests.memory: "32Gi"
    limits.cpu: "18000m"
    limits.memory: "64Gi"
    pods: "100"
    services: "30"

---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: "openshift.aaa-testprod.admin.users"
users: null

---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: "openshift.aaa-testprod.login.users"
users: null

---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: "openshift.aaa-testprod.appsupport.users"
users: null

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rb
  namespace: "aaa-test-prod"
subjects:
- kind: User
  name: system:serviceaccount:ucd-agent:ucd
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: "openshift.aaa-testprod.admin.users"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-rb
  namespace: "aaa-test-prod"
subjects:
- kind: Group
  name: openshift.devops.users
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: openshift.middleware.users
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: openshift.prod.login.users
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: "openshift.aaa-testprod.login.users"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appsupport-rb
  namespace: "aaa-test-prod"
subjects:
- kind: Group
  name: "openshift.aaa-testprod.appsupport.users"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: labcorp-app-support
  apiGroup: rbac.authorization.k8s.io
